# Generated by Django 2.2.9 on 2020-01-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puppet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of your micro frontend.', max_length=100)),
                ('domain_url', models.URLField(help_text='The domain in which the files are hosted.')),
                ('html_file', models.CharField(help_text='The name of the html file of the built SPA app.', max_length=200)),
                ('route', models.CharField(help_text='The django route where the app will be served', max_length=255, unique=True)),
            ],
        ),
    ]
