# Generated by Django 2.2.9 on 2020-01-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='microfrontend',
            name='name',
            field=models.CharField(default='Suite Application', help_text='Name of your micro frontend.', max_length=100),
            preserve_default=False,
        ),
    ]
